# NBA Analytics Dashboard Constants

CHART_HEIGHT_SMALL = 400
CHART_HEIGHT_MEDIUM = 600
CHART_HEIGHT_LARGE = 800
CHART_HEIGHT_EXTRA_LARGE = 1200

MARKER_SIZE_SMALL = 6
MARKER_SIZE_MEDIUM = 8
MARKER_SIZE_LARGE = 10
MARKER_SIZE_EXTRA_LARGE = 12

LINE_WIDTH_THIN = 2
LINE_WIDTH_MEDIUM = 3

NBA_BLUE = '#1f77b4'
NBA_ORANGE = '#ff7f0e'
NBA_GREEN = '#2ca02c'
NBA_RED = '#d62728'
NBA_PURPLE = '#9467bd'

CHART_BACKGROUND_DARK = 'darkblue'
CHART_BACKGROUND_LIGHT = 'lightblue'
TEXT_COLOR_WHITE = 'white'
TEXT_COLOR_BLACK = 'black'

LAKERS_PURPLE = '#552583'
WARRIORS_BLUE = '#006BB6'
BULLS_RED = '#CE1141'
CELTICS_GREEN = '#007A33'
HEAT_RED = '#98002E'

# Data Processing Constants
MIN_GAMES_THRESHOLD = 1
MAX_HISTORY_ENTRIES = 10
DEFAULT_CONFIDENCE_PERCENTAGE = 75

# Statistical Constants
LEAGUE_AVERAGE_WIN_PERCENTAGE = 0.500
LEAGUE_AVERAGE_POINTS_PER_GAME = 110.0
LEAGUE_AVERAGE_FIELD_GOAL_PCT = 0.460
LEAGUE_AVERAGE_THREE_POINT_PCT = 0.350
LEAGUE_AVERAGE_FREE_THROW_PCT = 0.770
LEAGUE_AVERAGE_REBOUNDS = 43.0
LEAGUE_AVERAGE_ASSISTS = 24.0
LEAGUE_AVERAGE_STEALS = 8.0
LEAGUE_AVERAGE_BLOCKS = 5.0
LEAGUE_AVERAGE_TURNOVERS = 14.0

# Performance Rating Thresholds
ELITE_WIN_PERCENTAGE = 0.600
ABOVE_AVERAGE_WIN_PERCENTAGE = 0.500
BELOW_AVERAGE_WIN_PERCENTAGE = 0.400

# UI Constants
COLUMNS_THREE_SPLIT = [1, 2, 1]
MAX_QUERY_HISTORY = 10
FILENAME_MAX_LENGTH = 30

# Font Sizes
FONT_SIZE_HEADER = 12
FONT_SIZE_BODY = 11

# Progress Steps
TOTAL_PROGRESS_STEPS = 6
STEP_PARSE_QUERY = 1
STEP_FETCH_DATA = 2
STEP_FETCH_STATS = 3
STEP_CREATE_VIZ = 4
STEP_PROCESS_DATA = 5
STEP_GENERATE_ANALYSIS = 6

EARLIEST_NBA_SEASON = 1996
LATEST_NBA_SEASON = 2024
CURRENT_SEASON_FORMAT = "{year}-{next_year_short}"

VERTICAL_SPACING_TIGHT = 0.06
VERTICAL_SPACING_NORMAL = 0.08
VERTICAL_SPACING_WIDE = 0.12
HORIZONTAL_SPACING_NORMAL = 0.10
HORIZONTAL_SPACING_WIDE = 0.15

CHART_ROW_FIRST = 1
CHART_ROW_SECOND = 2
CHART_ROW_THIRD = 3
CHART_ROW_FOURTH = 4

CHART_COL_FIRST = 1
CHART_COL_SECOND = 2

MAX_BINS_HISTOGRAM = 20
MAX_SEASONS_PREDICTION = 10
MIN_SEASONS_FOR_FRANCHISE = 5

PDF_PAGE_SIZE = "A4"
TEMP_FILE_PREFIX = "NBA_Report_"
PDF_FILE_EXTENSION = ".pdf"